name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        sudo apt-get install -y sshpass

    - name: Build and deploy
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        rsync -r -a -v -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude '.git/' --exclude '.github/' --exclude 'node_modules/' . $VPS_USER@$VPS_HOST:/app
        ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd /app && docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml up -d"
